# 扔还是不扔？

> 原文：<https://dev.to/calier/to-throw-or-not-to-throw-3dn9>

为了帮助我学习使用测试来编写代码，我一直在练习这个 TDD 形，罗伊·奥舍洛夫提供:。形让学习者写一个“添加”的方法，通过几个步骤建立它的功能。步骤 5 要求如果用负数调用该方法，它应该抛出一个异常。

在此之前，我听说过“抛出一个错误”的说法，并且知道异常是编程中的事情。我去 MDN 了解如何为自己编写代码，也去 Jest 文档了解如何为它编写测试。代码写好了，测试通过了，非常好。

几天后，我回到我最近的带回家的编码任务，添加一些额外的功能。我想添加的第一件事是一些错误处理，目的是通过检查程序的输入是否只包含执行过程中使用的特定字母来验证输入。通常我会记录错误，但是我记得我抛出异常的新发现...我认为这是一次很好的练习，我写了一个测试，然后写了一个方法来检查传入的字符串，如果遇到任何禁止的字符，就抛出一个错误。

然后我想知道我这样做实际上获得了什么。为什么我要使用 throw 而不仅仅是记录错误信息呢？老实说，我不知道哪一个比另一个更有价值，哪一个最适合特定的情况。我有一种模糊的感觉，觉得自己刚刚采用了一个过于复杂的解决方案来解决我的问题，只是为了实践这个新概念而炫耀。

剧透:在做了更多的研究后，发现我有点炫耀，但不太恰当。以下是我的发现:

当错误发生时，JavaScript 抛出一个异常，这意味着它将生成一个错误消息。这是它为你做的一件事；谁没见过 SyntaxError 或者 TypeError？“throw”语句允许您定义自定义错误。它们与其他一些语句一起使用:

*   try——使用 try 语句定义一个代码块，您希望在执行该代码块时对其进行错误检查
*   catch——如果 try 代码块导致错误，则执行用该语句定义的代码块
*   最后——不管 try 块的结果如何，都执行这段代码

“try”和“catch”语句成对出现。“throw”语句可以放在“try”块中，根据错误提供自定义消息:例如，您想检查用户从表单中输入的内容。如果用户输入了无效字符，错误信息可能是“输入未被识别”，或者如果他们使用了错误的大小写，错误信息可能是“输入必须是小写”。

在“catch”块中，您可以捕获刚刚发生的错误，并对其进行处理...将消息插入到一个字符串中，可能还添加了一些格式，这样您就可以向用户展示他们做错了什么。

你可以使用‘finally’总是向用户显示输入，这样他们就可以看到他们刚刚输入的内容。

我从 w3schools.com 网站上转述了一些精彩的解释:()。它帮我理清了头绪，所以如果你也想了解它，我建议你也去那里。使用“试用编辑器”进行一些练习。我可以肯定地看到使用“try”和“catch”以及“throw”来构建一些自定义错误处理方法的价值，并将在未来使用它，但我现在不需要它，在这个项目中！